package com.pampoukidis.streamcoretv.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme
val StreamCorePrimary = Color(0xFFEB5E28)
val StreamCoreOnPrimary = Color(0xFFFFFCF2)
val StreamCorePrimaryContainer = Color(0xFFFFDBCE)
val StreamCoreOnPrimaryContainer = Color(0xFF3A0B00)
val StreamCoreSecondary = Color(0xFF635D55)
val StreamCoreOnSecondary = Color(0xFFFFFCF2)
val StreamCoreSecondaryContainer = Color(0xFFCCC5B9)
val StreamCoreOnSecondaryContainer = Color(0xFF252422)
val StreamCoreTertiary = Color(0xFF403D39)
val StreamCoreOnTertiary = Color(0xFFFFFCF2)
val StreamCoreTertiaryContainer = Color(0xFFE6E1D9)
val StreamCoreOnTertiaryContainer = Color(0xFF1C1B17)
val StreamCoreBackground = Color(0xFFFFFCF2)
val StreamCoreOnBackground = Color(0xFF252422)
val StreamCoreSurface = Color(0xFFFFFCF2)
val StreamCoreOnSurface = Color(0xFF252422)
val StreamCoreSurfaceVariant = Color(0xFFCCC5B9)
val StreamCoreOnSurfaceVariant = Color(0xFF403D39)
val StreamCoreOutline = Color(0xFF7F7A72)
val StreamCoreOutlineVariant = Color(0xFFCCC5B9)
val StreamCoreError = Color(0xFFBA1A1A)
val StreamCoreOnError = Color(0xFFFFFFFF)
val StreamCoreErrorContainer = Color(0xFFFFDAD6)
val StreamCoreOnErrorContainer = Color(0xFF410002)

// Dark Theme
val StreamCoreDarkPrimary = Color(0xFFEB5E28)
val StreamCoreDarkOnPrimary = Color(0xFF3D1400)
val StreamCoreDarkPrimaryContainer = Color(0xFF732700)
val StreamCoreDarkOnPrimaryContainer = Color(0xFFFFDBCF)
val StreamCoreDarkSecondary = Color(0xFFCCC5B9)
val StreamCoreDarkOnSecondary = Color(0xFF342F29)
val StreamCoreDarkSecondaryContainer = Color(0xFF4B443D)
val StreamCoreDarkOnSecondaryContainer = Color(0xFFE9E1D4)
val StreamCoreDarkTertiary = Color(0xFFBFA892)
val StreamCoreDarkOnTertiary = Color(0xFF2C1B08)
val StreamCoreDarkTertiaryContainer = Color(0xFF432F1C)
val StreamCoreDarkOnTertiaryContainer = Color(0xFFDCCEBD)
val StreamCoreDarkBackground = Color(0xFF1A1918)
val StreamCoreDarkOnBackground = Color(0xFFE6E2D9)
val StreamCoreDarkSurface = Color(0xFF252422)
val StreamCoreDarkOnSurface = Color(0xFFE6E2D9)
val StreamCoreDarkSurfaceVariant = Color(0xFF403D39)
val StreamCoreDarkOnSurfaceVariant = Color(0xFFCCC5B9)
val StreamCoreDarkOutline = Color(0xFF968F86)
val StreamCoreDarkOutlineVariant = Color(0xFF4A4641)
val StreamCoreDarkError = Color(0xFFFFB4AB)
val StreamCoreDarkOnError = Color(0xFF690005)
val StreamCoreDarkErrorContainer = Color(0xFF93000A)
val StreamCoreDarkOnErrorContainer = Color(0xFFFFDAD6)